# frozen_string_literal: true

require 'active_support/core_ext/hash/keys'
require 'active_support/core_ext/string'
require 'active_support/core_ext/module/delegation'
require 'active_support/core_ext/hash/indifferent_access'
require 'json'
require 'time'

require 'rest-client'
require 'eventmachine'
require 'faye/websocket'

require_relative 'alpaca/news/api'
require_relative 'alpaca/news/api/base'
require_relative 'alpaca/news/api/configuration'
require_relative 'alpaca/news/api/error'
require_relative 'alpaca/news/api/models/event'
require_relative 'alpaca/news/api/models/news'
require_relative 'alpaca/news/api/rest/base'
require_relative 'alpaca/news/api/rest/client'
require_relative 'alpaca/news/api/rest/collection'
require_relative 'alpaca/news/api/rest/news'
require_relative 'alpaca/news/api/historical_news'
require_relative 'alpaca/news/api/realtime/base'
require_relative 'alpaca/news/api/realtime/client'
require_relative 'alpaca/news/api/realtime/news'
require_relative 'alpaca/news/api/realtime_news'
require_relative 'alpaca/news/api/version'
