on:
  pull_request:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: gem update --system 3.2.3
      - run: bundle exec rspec spec/
